(201, 'Naruto Shippuden', 'Action', 500, 'naruto_shippuden.png'),
(202, 'One Piece', 'Adventure', '1000+', 'one_piece.png'),
(203, 'Attack on Titan', 'Action', 87, 'attack_on_titan.png'),
(204, 'Demon Slayer: Kimetsu no Yaiba', 'Action', 44, 'demon_slayer.png'),
(205, 'My Hero Academia', 'Action', 138, 'my_hero_academia.png'),
(206, 'Dragon Ball Super', 'Action', 131, 'dragon_ball_super.png'),
(207, 'Sword Art Online', 'Sci-Fi', 96, 'sword_art_online.png'),
(208, 'Fullmetal Alchemist: Brotherhood', 'Adventure', 64, 'fma_brotherhood.png'),
(209, 'Jujutsu Kaisen', 'Action', 36, 'jujutsu_kaisen.png'),
(210, 'Tokyo Revengers', 'Drama', 37, 'tokyo_revengers.png'),
(211, 'Black Clover', 'Fantasy', 170, 'black_clover.png'),
(212, 'Bleach', 'Action', 366, 'bleach.png'),
(213, 'Fairy Tail', 'Fantasy', 328, 'fairy_tail.png'),
(214, 'Hunter x Hunter', 'Adventure', 148, 'hunter_x_hunter.png'),
(215, 'Death Note', 'Mystery', 37, 'death_note.png'),
(216, 'Steins;Gate', 'Sci-Fi', 24, 'steins_gate.png'),
(217, 'Erased', 'Mystery', 12, 'erased.png'),
(218, 'Re:Zero - Starting Life in Another World', 'Fantasy', 50, 'rezero.png'),
(219, 'A Silent Voice', 'Drama', 'Movie', 'a_silent_voice.png'),
(220, 'Your Name', 'Romance', 'Movie', 'your_name.png'),
(221, 'Weathering With You', 'Romance', 'Movie', 'weathering_with_you.png'),
(222, 'Clannad: After Story', 'Romance', 24, 'clannad_after_story.png'),
(223, 'Angel Beats!', 'Drama', 13, 'angel_beats.png'),
(224, 'K-On!', 'Music', 41, 'k_on.png'),
(225, 'Haikyuu!!', 'Sports', 85, 'haikyuu.png'),
(226, 'Kuroko no Basket', 'Sports', 75, 'kuroko_no_basket.png'),
(227, 'Yuri!!! on Ice', 'Sports', 12, 'yuri_on_ice.png'),
(228, 'The Promised Neverland', 'Thriller', 23, 'the_promised_neverland.png'),
(229, 'No Game No Life', 'Fantasy', 12, 'no_game_no_life.png'),
(230, 'Overlord', 'Fantasy', 52, 'overlord.png'),
(231, 'The Rising of the Shield Hero', 'Adventure', 38, 'shield_hero.png'),
(232, 'Made in Abyss', 'Adventure', 25, 'made_in_abyss.png'),
(233, 'The Seven Deadly Sins', 'Fantasy', 100, 'seven_deadly_sins.png'),
(234, 'Vinland Saga', 'Historical', 48, 'vinland_saga.png'),
(235, 'Chainsaw Man', 'Action', 12, 'chainsaw_man.png'),
(236, 'Blue Lock', 'Sports', 24, 'blue_lock.png'),
(237, 'Spy x Family', 'Comedy', 25, 'spy_x_family.png'),
(238, 'Dr. Stone', 'Sci-Fi', 35, 'dr_stone.png'),
(239, 'Mushoku Tensei: Jobless Reincarnation', 'Fantasy', 49, 'mushoku_tensei.png'),
(240, 'Toradora!', 'Romance', 25, 'toradora.png'),
(241, 'Horimiya', 'Romance', 13, 'horimiya.png'),
(242, 'Akame ga Kill!', 'Action', 24, 'akame_ga_kill.png'),
(243, 'Highschool of the Dead', 'Horror', 12, 'highschool_of_the_dead.png'),
(244, 'Psycho-Pass', 'Sci-Fi', 41, 'psycho_pass.png'),
(245, 'Code Geass: Lelouch of the Rebellion', 'Sci-Fi', 50, 'code_geass.png'),
(246, 'Neon Genesis Evangelion', 'Sci-Fi', 26, 'evangelion.png'),
(247, 'Cowboy Bebop', 'Sci-Fi', 26, 'cowboy_bebop.png'),
(248, 'Trigun', 'Action', 26, 'trigun.png'),
(249, 'Samurai Champloo', 'Action', 26, 'samurai_champloo.png'),
(250, 'Hellsing Ultimate', 'Horror', 10, 'hellsing_ultimate.png'),
(251, 'Ghost in the Shell', 'Sci-Fi', 'Movie', 'ghost_in_the_shell.png'),
(252, 'Paprika', 'Fantasy', 'Movie', 'paprika.png'),
(253, 'Spirited Away', 'Fantasy', 'Movie', 'spirited_away.png'),
(254, 'Princess Mononoke', 'Fantasy', 'Movie', 'princess_mononoke.png'),
(255, 'Howl\`s Moving Castle', 'Fantasy', 'Movie', 'howls_moving_castle.png'),
(256, 'Nausicaä of the Valley of the Wind', 'Adventure', 'Movie', 'nausicaa.png'),
(257, 'Castle in the Sky', 'Adventure', 'Movie', 'castle_in_the_sky.png'),
(258, 'Ponyo', 'Fantasy', 'Movie', 'ponyo.png'),
(259, 'Grave of the Fireflies', 'Drama', 'Movie', 'grave_of_the_fireflies.png'),
(260, 'My Neighbor Totoro', 'Fantasy', 'Movie', 'totoro.png'),
(261, 'Paranoia Agent', 'Mystery', 13, 'paranoia_agent.png'),
(262, 'Ergo Proxy', 'Sci-Fi', 23, 'ergo_proxy.png'),
(263, 'Berserk (1997)', 'Action', 25, 'berserk_1997.png'),
(264, 'Monster', 'Mystery', 74, 'monster.png'),
(265, 'Texhnolyze', 'Sci-Fi', 22, 'texhnolyze.png'),
(266, 'Great Teacher Onizuka', 'Comedy', 43, 'gto.png'),
(267, 'Golden Boy', 'Comedy', 6, 'golden_boy.png'),
(268, 'JoJo\`s Bizarre Adventure', 'Action', '1000+', 'jojo.png'),
(269, 'Fate/Zero', 'Fantasy', 25, 'fate_zero.png'),
(270, 'Fate/stay night: Unlimited Blade Works', 'Fantasy', 26, 'fate_ubw.png'),
(271, 'Kara no Kyoukai', 'Fantasy', 'Movie', 'kara_no_kyoukai.png'),
(272, 'Black Lagoon', 'Action', 24, 'black_lagoon.png'),
(273, 'Dorohedoro', 'Fantasy', 12, 'dorohedoro.png'),
(274, 'Zombieland Saga', 'Comedy', 24, 'zombieland_saga.png'),
(275, 'Konosuba', 'Comedy', 20, 'konosuba.png'),
(276, 'Is It Wrong to Try to Pick Up Girls in a Dungeon?', 'Fantasy', 59, 'danmachi.png'),
(277, 'Shokugeki no Soma', 'Cooking', 86, 'shokugeki_no_soma.png'),
(278, 'Beastars', 'Drama', 24, 'beastars.png'),
(279, 'Aggretsuko', 'Comedy', 50, 'aggretsuko.png'),
(280, 'Gintama', 'Comedy', '1000+', 'gintama.png'),
(281, 'Ranma ½', 'Comedy', 161, 'ranma.png'),
(282, 'Nodame Cantabile', 'Music', 47, 'nodame_cantabile.png'),
(283, 'The Melancholy of Haruhi Suzumiya', 'Sci-Fi', 28, 'haruhi_suzumiya.png'),
(284, 'Lucky☆Star', 'Comedy', 24, 'lucky_star.png'),
(285, 'Kobayashi-san Chi no Maid Dragon', 'Comedy', 25, 'maid_dragon.png'),
(286, 'Sk8 the Infinity', 'Sports', 12, 'sk8.png'),
(287, 'Ballroom e Youkoso', 'Sports', 24, 'ballroom.png'),
(288, 'Aoashi', 'Sports', 24, 'aoashi.png'),
(289, 'Boku no Pico', 'Controversial', 3, 'boku_no_pico.png'),
(290, 'Yakitate!! Japan', 'Cooking', 69, 'yakitate_japan.png'),
(291, 'Slam Dunk', 'Sports', 101, 'slam_dunk.png'),
(292, 'Hajime no Ippo', 'Sports', 126, 'hajime_no_ippo.png'),
(293, 'Bakuman.', 'Drama', 75, 'bakuman.png'),
(294, 'March Comes in Like a Lion', 'Drama', 44, 'march_lion.png'),
(295, 'Anohana: The Flower We Saw That Day', 'Drama', 11, 'anohana.png'),
(296, 'Barakamon', 'Comedy', 12, 'barakamon.png'),
(297, 'Silver Spoon', 'Comedy', 22, 'silver_spoon.png'),
(298, 'Nichijou', 'Comedy', 26, 'nichijou.png'),
(299, 'Azumanga Daioh', 'Comedy', 26, 'azumanga.png'),
(300, 'Kaichou wa Maid-sama!', 'Romance', 26, 'maid_sama.png');